Repository JorgeLVilla/modern-news-app, pull requests merged in 2021-09, with the labels that each got.

#30 Jv 3 show top news main
  modern-news-app/package-lock.json
  modern-news-app/src/App.tsx
  modern-news-app/src/assets/magazine 2.png
  modern-news-app/src/components/Main.tsx
  modern-news-app/src/components/TodayNews.tsx
  modern-news-app/src/components/TopNews.tsx
  modern-news-app/src/models/Articles.ts
  modern-news-app/src/models/TodayArticles 2.ts
  modern-news-app/src/style/Articles.style.ts
  modern-news-app/src/style/NavButton.style.ts
  modern-news-app/src/util/fetchApi.ts
Labels: enhancement

#33 Lp 32 app fix
  modern-news-app/src/App.tsx
  modern-news-app/src/components/Main.tsx
  modern-news-app/src/models/Articles.ts
  modern-news-app/src/style/Articles.style.ts
  modern-news-app/src/util/fetchApi.ts
Labels: bug, enhancement

#35 removed duplicate TodayArticles file
  modern-news-app/src/models/TodayArticles 2.ts
Labels: bug

#36 feat(news-articles):make articles in main clickable to expand them an…
  modern-news-app/src/components/Main.tsx
Labels: enhancement

#40 feat(news-articles):add more details in the news articles and in their expanded view
  modern-news-app/src/components/Main.tsx
  modern-news-app/src/style/Articles.style.ts
Labels: enhancement

#42 Jv 39 home button
  modern-news-app/src/App.tsx
  modern-news-app/src/components/Navbar.tsx
Labels: enhancement

#44 feat(nav-icons):gives pointer cursor to icons
  modern-news-app/src/components/Navbar.tsx
Labels: enhancement

#45 Lp 41 articles styles
  modern-news-app/src/components/Main.tsx
  modern-news-app/src/style/Articles.style.ts
Labels: enhancement

#48 feat(articles):added the correct details in article card
  modern-news-app/src/components/TodayNews.tsx
  modern-news-app/src/components/TopNews.tsx
Labels: enhancement

#50 Lp 47 back home btn
  modern-news-app/src/App.tsx
  modern-news-app/src/assets/back.png
  modern-news-app/src/components/Main.tsx
Labels: enhancement

#52 Lp 51 on hover effect
  modern-news-app/src/components/Navbar.tsx
  modern-news-app/src/style/Articles.style.ts
Labels: enhancement

#54 feat(main-page):Adds onclick feature to expand articles
  modern-news-app/src/components/Main.tsx
  modern-news-app/src/components/TodayNews.tsx
  modern-news-app/src/components/TopNews.tsx
Labels: enhancement

#55 Ds 27 style top news desktop
  modern-news-app/public/index.html
  modern-news-app/src/App.css
  modern-news-app/src/App.tsx
  modern-news-app/src/components/Navbar.tsx
  modern-news-app/src/components/TodayNews.tsx
  modern-news-app/src/components/TopNews.tsx
  modern-news-app/src/models/Articles.ts
  modern-news-app/src/models/TodayArticles.ts
  modern-news-app/src/style/Articles.style.ts
  modern-news-app/src/style/SectionTitles.style.ts
  modern-news-app/src/style/Wrappers.style.ts
  modern-news-app/src/util/fetchApi.ts
Labels: enhancement

#56 Lp 53 article components
  modern-news-app/src/components/Article.tsx
  modern-news-app/src/components/ExpandedArticle.tsx
  modern-news-app/src/components/Main.tsx
  modern-news-app/src/components/TodayNews.tsx
  modern-news-app/src/components/TopNews.tsx
  modern-news-app/src/models/Articles.ts
  modern-news-app/src/style/Articles.style.ts
Labels: enhancement

#65 bug(article):close button shows pointer on hover
  modern-news-app/src/style/Articles.style.ts
Labels: bug

#67 Lp 63 screen stays on article
  firebase-debug.log
  modern-news-app/.firebase/hosting.YnVpbGQ.cache
  modern-news-app/.firebaserc
  modern-news-app/firebase.json
  modern-news-app/src/components/Article.tsx
  modern-news-app/src/components/ExpandedArticle.tsx
  modern-news-app/src/style/Articles.style.ts
Labels: bug

#68 bug(back-button):gives pointer cursor to back button
  modern-news-app/src/components/Main.tsx
Labels: bug

#69 Ds 64 display default image
  modern-news-app/src/assets/magazine 2.png
  modern-news-app/src/assets/noimageavailable.jpg
  modern-news-app/src/components/Article.tsx
  modern-news-app/src/components/ExpandedArticle.tsx
  modern-news-app/src/components/Main.tsx
  modern-news-app/src/components/TodayNews.tsx
Labels: bug

#70 Lp 66 20 articles on main
  modern-news-app/src/App.tsx
Labels: bug

#73 bug(back-button):gives go home label to home button on hover
  modern-news-app/src/components/Main.tsx
Labels: bug

#76 Lp 59 reset enlarged article index
  modern-news-app/src/App.tsx
  modern-news-app/src/components/Article.tsx
  modern-news-app/src/components/Main.tsx
  modern-news-app/src/components/Navbar.tsx
  modern-news-app/src/components/TodayNews.tsx
  modern-news-app/src/components/TopNews.tsx
Labels: bug

#79 bug(news-title): top news title was duplicated on main screen
  modern-news-app/src/components/TodayNews.tsx
Labels: bug

#81 Lp 78 one half article fix
  modern-news-app/src/App.tsx
  modern-news-app/src/style/Articles.style.ts
Labels: bug

#84 feat(app): adds a backend to our app
  modern-news-app/src/util/fetchApi.ts
Labels: enhancement

#87 docs(readme): add description to readme.md, and update package.json
  modern-news-app/package.json
Labels: documentation

#88 docs(readme): add readme file
  README.md
Labels: documentation
